import { prisma } from "@/lib/prisma";

export type ClientMergeImpactRow = { label: string; count: number };

/** Conteggi record collegati a un cliente (per anteprima merge / wizard). */
export async function getClientMergeImpact(clientId: string): Promise<ClientMergeImpactRow[]> {
  const [
    posts,
    webhooks,
    flowTasks,
    memoryItems,
    opportunities,
    assets,
    contacts,
    tickets,
    outreachDrafts,
    outreachSequences,
    commercialServices,
    digitalAudits,
    financeEntries,
    milestones,
    timeEntries,
    retailContracts,
    storeSales,
    campaignEnrollments,
    socialAccounts,
    analyticsMetrics,
    competitors,
    commitments,
    onboardingItems,
  ] = await Promise.all([
    prisma.postItem.count({ where: { clientId } }),
    prisma.webhookSubscription.count({ where: { clientId } }),
    prisma.flowTask.count({ where: { relatedClientId: clientId } }),
    prisma.memoryItem.count({ where: { relatedClientId: clientId } }),
    prisma.opportunity.count({ where: { clientId } }),
    prisma.asset.count({ where: { clientId } }),
    prisma.clientContact.count({ where: { clientId } }),
    prisma.clientTicket.count({ where: { clientId } }),
    prisma.outreachDraft.count({ where: { clientId } }),
    prisma.outreachSequence.count({ where: { clientId } }),
    prisma.clientCommercialService.count({ where: { clientId } }),
    prisma.digitalAudit.count({ where: { clientId } }),
    prisma.financeEntry.count({ where: { clientId } }),
    prisma.clientMilestone.count({ where: { clientId } }),
    prisma.timeEntry.count({ where: { clientId } }),
    prisma.clientRetailContract.count({ where: { clientId } }),
    prisma.storeSale.count({ where: { clientId } }),
    prisma.campaignEnrollment.count({ where: { clientId } }),
    prisma.socialAccount.count({ where: { clientId } }),
    prisma.analyticsMetric.count({ where: { clientId } }),
    prisma.competitor.count({ where: { clientId } }),
    prisma.clientCommitment.count({ where: { clientId } }),
    prisma.clientOnboardingItem.count({ where: { clientId } }),
  ]);

  return [
    { label: "Post", count: posts },
    { label: "Webhook", count: webhooks },
    { label: "Task Flow", count: flowTasks },
    { label: "Memorie", count: memoryItems },
    { label: "Opportunità", count: opportunities },
    { label: "Asset", count: assets },
    { label: "Contatti", count: contacts },
    { label: "Ticket", count: tickets },
    { label: "Reach bozze", count: outreachDrafts },
    { label: "Reach sequenze", count: outreachSequences },
    { label: "Servizi commerciali", count: commercialServices },
    { label: "Audit digitali", count: digitalAudits },
    { label: "Finance", count: financeEntries },
    { label: "Milestone", count: milestones },
    { label: "Time entry", count: timeEntries },
    { label: "Contratti retail", count: retailContracts },
    { label: "Vendite negozio", count: storeSales },
    { label: "Iscrizioni campagne", count: campaignEnrollments },
    { label: "Account social", count: socialAccounts },
    { label: "Metriche analytics", count: analyticsMetrics },
    { label: "Competitor", count: competitors },
    { label: "Impegni", count: commitments },
    { label: "Onboarding", count: onboardingItems },
  ];
}
